import { create } from 'zustand';
import { Channel } from '@tauri-apps/api/core';
import * as ipc from '../lib/ipc';
import type { AgentEvent, AgentRoleKey, ChatMessage, ChatSessionMeta, PhaseRecord } from '../types';
import { StreamTextBuffer, type FlushedText } from './streamBuffer';

export interface UiToolCall {
  callId: string;
  toolName: string;
  argumentsJson: string;
  output?: string;
  status: 'running' | 'done' | 'error';
}

export interface UiMessage {
  id: string;
  role: 'user' | 'assistant' | 'error';
  content: string;
  /** Streamed reasoning/thinking of the agent (shown collapsible). */
  thinking?: string;
  toolCalls?: UiToolCall[];
  streaming?: boolean;
  /** Estimated input tokens used by THIS agent phase (per-role cost). */
  tokensIn?: number;
  /** Estimated output tokens generated by THIS agent phase. */
  tokensOut?: number;
  /** Cached input tokens reported by the hub/provider (context caching). */
  cachedIn?: number;
  /** Legacy combined total (run-wide) — kept for compatibility. */
  tokensUsed?: number;
  agentRole?: AgentRoleKey;
  phaseLabel?: string;
  phaseModel?: string;
  phaseSummary?: string;
  editSessionId?: string | null;
  /** Id of the agent run this message belongs to (groups one run into one box). */
  runId?: string;
  /** When true the agent section is collapsed. New phases auto-minimize older ones. */
  minimized?: boolean;
}

export interface PendingExternalRequest {
  requestId: string;
  path: string;
  reason: string;
  kind: string;
}

interface AgentState {
  sessions: ChatSessionMeta[];
  activeSessionId: string | null;
  historyMessages: ChatMessage[];
  liveMessages: UiMessage[];
  pendingExternalRequests: PendingExternalRequest[];
  pendingPlanDecision: PendingPlanDecision | null;
  /** Thinker-direction checkpoint: kesimpulan sementara menunggu review user. */
  pendingDirection: PendingDirection | null;
  busy: boolean;
  error: string | null;
  autoApprove: boolean;
  planGateEnabled: boolean;
  hasGeminiKey: boolean;
  hasHubKey: boolean;
  /** True when any custom provider (Settings -> Providers) has a saved key. */
  hasCustomProvider: boolean;
  showHistory: boolean;
  swarmMode: boolean;
  lastEditSessionId: string | null;
  /** Run id of the currently active agent run (used to cancel it). */
  currentRunId: string | null;
  /** A run that failed and can be continued from its last checkpoint. */
  resumeTarget: { sessionId: string; runId: string } | null;

  init: () => Promise<void>;
  checkKey: () => Promise<void>;
  setAutoApprove: (v: boolean) => void;
  setPlanGateEnabled: (v: boolean) => void;
  setSwarmMode: (v: boolean) => void;

  newChat: () => void;
  loadHistory: (sessionId: string) => Promise<void>;
  deleteSession: (sessionId: string) => Promise<void>;
  toggleHistoryPanel: () => void;

  send: (prompt: string, refreshWorkspace?: () => void) => Promise<void>;
  resumeRun: () => Promise<void>;
  cancelRun: () => void;
  revertEditSession: (sessionId?: string, refreshWorkspace?: () => void) => Promise<void>;
  bindExternalEvents: () => void;
  approveExternalAccess: (requestId: string) => Promise<void>;
  denyExternalAccess: (requestId: string) => Promise<void>;
  resolvePlanDecision: (decision: 'execute' | 'revise' | 'review', note?: string) => Promise<void>;
  resolveDirection: (decision: 'lanjut' | 'ubah', note?: string) => Promise<void>;
}

let msgCounter = 0;
const nextId = () => `m${++msgCounter}_${Date.now()}`;

// ── Transcript mapping (backend-sent, display-only) ────────────────────────
// The backend persists every swarm phase as `PhaseRecord[]` in the session
// file (`ChatSessionData.transcript`). The frontend maps them to the same
// `UiMessage[]` shape the live view renders, so history replays exactly like
// the original run. `session.messages` (the ledger) is NEVER used for replay —
// it is the LLM context and would pollute the display.

export interface PendingPlanDecision {
  requestId: string;
  planMarkdown: string;
  planFilePath: string;
  round: number;
  tasksCount: number;
  latestNote: string | null;
}

export interface PendingDirection {
  requestId: string;
  conclusion: string;
}

function mapTranscript(transcript: PhaseRecord[]): UiMessage[] {
  return transcript.map((rec) => ({
    id: nextId(),
    role: 'assistant',
    content: rec.text,
    thinking: rec.thinking,
    toolCalls: rec.tool_calls.map((tc) => ({
      callId: tc.call_id,
      toolName: tc.tool_name,
      argumentsJson: tc.arguments_json,
      output: tc.output,
      status: tc.status as UiToolCall['status'],
    })),
    agentRole: rec.role as AgentRoleKey | undefined,
    phaseLabel: rec.label,
    phaseModel: rec.model,
    phaseSummary: rec.summary,
    runId: rec.run_id,
    minimized: true,
  }));
}

function mapMessages(messages: ChatMessage[]): UiMessage[] {
  const out: UiMessage[] = [];
  for (const m of messages) {
    if (m.role === 'User') {
      out.push({ id: nextId(), role: 'user', content: m.content });
    } else if (m.role === 'Assistant' || m.role === 'System') {
      out.push({
        id: nextId(),
        role: 'assistant',
        content: m.content,
        minimized: true,
      });
    }
  }
  return out;
}

/// Single shared interval so calling `init()` multiple times (App mount +
/// AgentPanel mount) never starts duplicate refresh/check timers.
let refreshTimer: ReturnType<typeof setInterval> | null = null;

export const useAgent = create<AgentState>((set, get) => ({
  sessions: [],
  activeSessionId: null,
  historyMessages: [],
  liveMessages: [],
  pendingExternalRequests: [],
  pendingPlanDecision: null,
  pendingDirection: null,
  busy: false,
  error: null,
  autoApprove: true,
  planGateEnabled: true,
  hasGeminiKey: false,
  hasHubKey: false,
  hasCustomProvider: false,
  showHistory: false,
  swarmMode: true,
  lastEditSessionId: null,
  currentRunId: null,
  resumeTarget: null,

  init: async () => {
    await get().checkKey();
    // Re-probe once shortly after startup: the very first IPC invoke can race
    // webview initialization, which used to leave the badge red until the user
    // happened to open Settings (which triggers another checkKey).
    setTimeout(() => {
      get().checkKey();
    }, 3000);
    try {
      const sessions = await ipc.chatListSessions();
      set({ sessions });
    } catch {
      /* app data dir not ready until a project is opened */
    }
    // Load the Plan Approval Gate toggle from the persisted agent config.
    try {
      const cfg = await ipc.agentConfigGet();
      set({ planGateEnabled: cfg.plan_gate_enabled ?? true });
    } catch {
      /* config not available yet — keep default ON */
    }
    // Keep the rotating Kuda Hub session key fresh: the server rotates it every
    // 30 min; refresh at most 5 min before expiry, and only while the agent is idle.
    if (!refreshTimer) {
      refreshTimer = setInterval(() => {
        if (!useAgent.getState().busy) {
          ipc.agentEnsureHubSession().catch(() => {
            /* hub offline */
          });
          get().checkKey();
        }
      }, 30000);
    }
  },

  checkKey: async () => {
    // Each probe is independent: a keychain error on one provider must never
    // wipe out the other's status (this caused the "No API key" badge staying
    // stale after a successful hub login).
    let hasGemini = false;
    let hasHub = false;
    let hasCustomProvider = false;
    try {
      hasGemini = await ipc.agentHasKey('gemini');
    } catch {
      hasGemini = false;
    }
    try {
      hasHub = await ipc.agentHasHubCredentials();
    } catch {
      hasHub = false;
    }
    try {
      // The provider config (Settings -> Providers) stores each provider's key
      // under `provider_key.<id>`, which `provider_list` reports as `has_key`.
      // The badge must not claim "No API key" when a custom provider (DeepSeek,
      // OpenRouter, ...) is configured with a key.
      const providers = await ipc.providerList();
      hasCustomProvider = providers.some((p) => p.has_key);
    } catch {
      hasCustomProvider = false;
    }
    set({
      hasGeminiKey: hasGemini || hasHub || hasCustomProvider,
      hasHubKey: hasHub,
      hasCustomProvider,
    });
  },

  setAutoApprove: (v) => set({ autoApprove: v }),

  setPlanGateEnabled: async (v) => {
    set({ planGateEnabled: v });
    try {
      const cfg = await ipc.agentConfigGet();
      await ipc.agentConfigSet({ ...cfg, plan_gate_enabled: v });
    } catch {
      /* backend config not ready — toggle applies to this session only */
    }
  },

  setSwarmMode: (v) => set({ swarmMode: v }),

  bindExternalEvents: () => {
    const channel = new Channel<AgentEvent>();
    channel.onmessage = (event) => {
      const kind = event.kind;
      if ('ExternalAccessRequest' in kind) {
        const { request_id, path, reason, kind: reqKind } = kind.ExternalAccessRequest;
        set((s) => ({
          pendingExternalRequests: s.pendingExternalRequests.some(
            (r) => r.requestId === request_id,
          )
            ? s.pendingExternalRequests
            : [
                ...s.pendingExternalRequests,
                { requestId: request_id, path, reason, kind: reqKind },
              ],
        }));
      }
      if ('ExternalAccessResolved' in kind) {
        const { request_id } = kind.ExternalAccessResolved;
        set((s) => ({
          pendingExternalRequests: s.pendingExternalRequests.filter(
            (r) => r.requestId !== request_id,
          ),
        }));
      }
    };
    ipc.bindExternalAccessEvents(channel).catch(() => {
      /* backend not ready (e.g. before a project is opened) */
    });
  },

  newChat: () => {
    resetStreamBuffer();
    set({
      activeSessionId: null,
      historyMessages: [],
      liveMessages: [],
      error: null,
      pendingDirection: null,
      resumeTarget: null,
    });
  },

  toggleHistoryPanel: () => set((s) => ({ showHistory: !s.showHistory })),

  loadHistory: async (sessionId) => {
    try {
      resetStreamBuffer();
      const data = await ipc.chatLoadSession(sessionId);
      // Backend transcript is the display source of truth. Sessions created
      // before the ledger/transcript feature (or plain chats) fall back to
      // the backend messages (user prompt + final answer).
      const transcript = data.transcript?.length
        ? mapTranscript(data.transcript)
        : null;
      set({
        activeSessionId: sessionId,
        historyMessages: transcript ? [] : data.messages,
        liveMessages: transcript ?? mapMessages(data.messages),
        error: null,
        showHistory: false,
        resumeTarget: null,
      });
    } catch (err) {
      set({ error: String(err) });
    }
  },

  deleteSession: async (sessionId) => {
    try {
      await ipc.chatDeleteSession(sessionId);
      const sessions = await ipc.chatListSessions();
      set((s) => ({
        sessions,
        activeSessionId: s.activeSessionId === sessionId ? null : s.activeSessionId,
        historyMessages: s.activeSessionId === sessionId ? [] : s.historyMessages,
      }));
    } catch (err) {
      set({ error: String(err) });
    }
  },

  send: async (prompt, refreshWorkspace) => {
    const { busy, activeSessionId, autoApprove, swarmMode } = get();
    if (busy || !prompt.trim()) return;

    // Generate the run id up front so it can cancel the run while it is active
    // (the backend echoes it back as edit_session_id).
    const runId =
      typeof crypto !== 'undefined' && crypto.randomUUID
        ? crypto.randomUUID()
        : `run_${Date.now()}`;

    const userMsg: UiMessage = { id: nextId(), role: 'user', content: prompt, runId };
    const userMsgId = userMsg.id;
    // In swarm mode the assistant bubbles are created per PhaseStarted event
    // (one bubble per role); legacy mode uses a single assistant bubble.
    // Every message of a run shares `runId` so the UI can render the whole run
    // as a single box with one collapsible section per agent.
    const seedMessages = swarmMode
      ? [userMsg]
      : [
          userMsg,
          {
            id: nextId(),
            role: 'assistant' as const,
            content: '',
            toolCalls: [],
            streaming: true,
            runId,
            minimized: false,
          },
        ];

    set((s) => ({
      liveMessages: [...s.liveMessages, ...seedMessages],
      pendingExternalRequests: [],
      pendingPlanDecision: null,
      pendingDirection: null,
      busy: true,
      error: null,
      lastEditSessionId: null,
      currentRunId: runId,
      resumeTarget: null,
    }));
    resetStreamBuffer();

    const channel = new Channel<AgentEvent>();
    const { wasTouched } = bindRunChannel(channel, runId);

    try {
      const result = swarmMode
        ? await ipc.agentSwarmChat(prompt, activeSessionId, autoApprove, channel, runId)
        : await ipc.agentChat(prompt, activeSessionId, autoApprove, channel, runId);
      set((s) => ({
        activeSessionId: result.chat_session_id,
        lastEditSessionId: result.edit_session_id,
        liveMessages: s.liveMessages.map((m) =>
          m.id === userMsgId ? { ...m, editSessionId: result.edit_session_id } : m,
        ),
      }));
      try {
        const sessions = await ipc.chatListSessions();
        set({ sessions });
      } catch { /* ignore */ }
      if (wasTouched() && refreshWorkspace) refreshWorkspace();
    } catch (err) {
      set((s) => ({
        error: String(err),
        resumeTarget: { sessionId: s.activeSessionId ?? '', runId },
        liveMessages: s.liveMessages.map((m) => ({ ...m, streaming: false })),
      }));
    } finally {
      flushStreamText();
      flushStreamThinking();
      set({ busy: false, pendingExternalRequests: [], pendingPlanDecision: null, pendingDirection: null, currentRunId: null });
    }
  },

  resumeRun: async () => {
    const target = get().resumeTarget;
    if (!target || get().busy) return;
    set({
      error: null,
      pendingExternalRequests: [],
      pendingPlanDecision: null,
      pendingDirection: null,
      busy: true,
      currentRunId: target.runId,
    });
    resetStreamBuffer();
    const channel = new Channel<AgentEvent>();
    const { wasTouched } = bindRunChannel(channel, target.runId);
    try {
      const result = await ipc.agentResumeRun(target.sessionId, target.runId, get().autoApprove, channel);
      set((s) => ({
        activeSessionId: result.chat_session_id,
        lastEditSessionId: result.edit_session_id,
        resumeTarget: null,
        liveMessages: s.liveMessages.map((m) =>
          m.editSessionId === result.edit_session_id ? { ...m, streaming: false } : m,
        ),
      }));
      try {
        const sessions = await ipc.chatListSessions();
        set({ sessions });
      } catch { /* ignore */ }
      if (wasTouched()) {
        const { reloadOpenTabsFromDisk } = await import('../store/workspace');
        reloadOpenTabsFromDisk();
      }
    } catch (err) {
      // Keep resumeTarget so the user can retry; the backend checkpoint persists.
      set((s) => ({
        error: String(err),
        liveMessages: s.liveMessages.map((m) => ({ ...m, streaming: false })),
      }));
    } finally {
      flushStreamText();
      flushStreamThinking();
      set({ busy: false, pendingExternalRequests: [], pendingPlanDecision: null, pendingDirection: null, currentRunId: null });
    }
  },

  cancelRun: () => {
    const runId = get().currentRunId;
    if (runId) ipc.agentCancelRun(runId);
  },

  revertEditSession: async (sessionId, refreshWorkspace) => {
    const target = sessionId ?? get().lastEditSessionId;
    if (!target) return;
    try {
      const reverted = await ipc.historyRevertSession(target);
      if (reverted.length === 0) {
        alert('Nothing to revert: this run did not edit any files.');
      }
      set((s) => ({
        lastEditSessionId: s.lastEditSessionId === target ? null : s.lastEditSessionId,
        liveMessages: s.liveMessages.map((m) =>
          m.editSessionId === target ? { ...m, editSessionId: null } : m,
        ),
      }));
      if (refreshWorkspace) refreshWorkspace();
    } catch (err) {
      set({ error: String(err) });
    }
  },

  approveExternalAccess: async (requestId) => {
    try {
      await ipc.agentApproveExternalAccess(requestId);
    } catch (err) {
      set({ error: String(err) });
    }
  },

  denyExternalAccess: async (requestId) => {
    try {
      await ipc.agentDenyExternalAccess(requestId);
    } catch (err) {
      set({ error: String(err) });
    }
  },

  resolvePlanDecision: async (decision, note) => {
    const pending = get().pendingPlanDecision;
    if (!pending) return;
    try {
      await ipc.agentResolvePlanDecision(pending.requestId, decision, note);
    } catch (err) {
      set({ error: String(err) });
    }
  },

  resolveDirection: async (decision, note) => {
    const pending = get().pendingDirection;
    if (!pending) return;
    try {
      await ipc.agentResolveDirectionDecision(pending.requestId, decision, note);
    } catch (err) {
      set({ error: String(err) });
    }
  },
}));

/// Stream text coalescing --------------------------------------------------
/// Coalesces ThoughtDelta chunks into a single Zustand set per animation frame
/// so the UI re-renders at most ~60fps instead of once per backend delta.
/// Module scope is safe: only one run is active at a time (guarded by `busy`).

/// Shared event handler for a live agent run. Used by both `send` (new prompt)
/// and `resumeRun` (continue a failed run from its checkpoint) so the two paths
/// render the same way. Returns a getter for whether any tool call completed
/// (so the caller can refresh the workspace when the run edited files).
function bindRunChannel(
  channel: Channel<AgentEvent>,
  runId: string,
): { wasTouched: () => boolean } {
  let touchedFiles = false;
  channel.onmessage = (event) => {
    const kind = event.kind;

    // Any non-text event must flush coalesced deltas synchronously first so
    // text→tool→text ordering stays intact across phase boundaries.
    if (!('ThoughtDelta' in kind) && !('ThinkingDelta' in kind)) {
      flushStreamText();
      flushStreamThinking();
    }

    if ('Error' in kind) {
      useAgent.setState({ error: kind.Error });
    }
    if ('ToolCallCompleted' in kind) {
      touchedFiles = true;
    }

    if ('ExternalAccessRequest' in kind) {
      const { request_id, path, reason, kind: reqKind } = kind.ExternalAccessRequest;
      useAgent.setState((s) => ({
        pendingExternalRequests: s.pendingExternalRequests.some(
          (r) => r.requestId === request_id,
        )
          ? s.pendingExternalRequests
          : [
              ...s.pendingExternalRequests,
              { requestId: request_id, path, reason, kind: reqKind },
            ],
      }));
      return;
    }

    if ('ExternalAccessResolved' in kind) {
      const { request_id } = kind.ExternalAccessResolved;
      useAgent.setState((s) => ({
        pendingExternalRequests: s.pendingExternalRequests.filter(
          (r) => r.requestId !== request_id,
        ),
      }));
      return;
    }

    if ('PlanDecisionRequest' in kind) {
      const { request_id, plan_markdown, plan_file_path, round, tasks_count, latest_note } = kind.PlanDecisionRequest;
      useAgent.setState({
        pendingPlanDecision: {
          requestId: request_id,
          planMarkdown: plan_markdown,
          planFilePath: plan_file_path,
          round,
          tasksCount: tasks_count,
          latestNote: latest_note,
        },
      });
      return;
    }

    if ('PlanDecisionResolved' in kind) {
      const { request_id } = kind.PlanDecisionResolved;
      useAgent.setState((s) =>
        s.pendingPlanDecision?.requestId === request_id
          ? { pendingPlanDecision: null }
          : s,
      );
      return;
    }

    if ('DirectionDecisionRequest' in kind) {
      const { request_id, conclusion } = kind.DirectionDecisionRequest;
      useAgent.setState({ pendingDirection: { requestId: request_id, conclusion } });
      return;
    }

    if ('DirectionDecisionResolved' in kind) {
      const { request_id } = kind.DirectionDecisionResolved;
      useAgent.setState((s) =>
        s.pendingDirection?.requestId === request_id
          ? { pendingDirection: null }
          : s,
      );
      return;
    }

    if ('PhaseStarted' in kind) {
      const { role, label, model } = kind.PhaseStarted;
      useAgent.setState((s) => {
        // Auto-minimize every finished agent section of this run so only the
        // newly started agent stays expanded (keeps the run box tidy).
        const previous = s.liveMessages.map((m) =>
          m.role === 'assistant' && m.runId === runId
            ? { ...m, minimized: true, streaming: false }
            : m,
        );
        return {
          liveMessages: [
            ...previous,
            {
              id: nextId(),
              role: 'assistant',
              content: '',
              toolCalls: [],
              streaming: true,
              agentRole: role,
              phaseLabel: label,
              phaseModel: model,
              runId,
              minimized: false,
            },
          ],
        };
      });
      return;
    }

    if ('ThoughtDelta' in kind) {
      const msgs = useAgent.getState().liveMessages;
      const last = msgs[msgs.length - 1];
      if (!last || last.role !== 'assistant') return;
      enqueueStreamDelta(last.id, kind.ThoughtDelta);
      return;
    }

    if ('ThinkingDelta' in kind) {
      const msgs = useAgent.getState().liveMessages;
      const last = msgs[msgs.length - 1];
      if (!last || last.role !== 'assistant') return;
      enqueueThinkingDelta(last.id, kind.ThinkingDelta);
      return;
    }

    useAgent.setState((s) => {
      const messages = [...s.liveMessages];
      const lastIdx = messages.length - 1;
      const last = messages[lastIdx];
      if (!last || last.role !== 'assistant') return s;

      let updated: UiMessage = last;

      if ('ToolCallStarted' in kind) {
        const { call_id, tool_name, arguments_json } = kind.ToolCallStarted;
        updated = {
          ...last,
          toolCalls: [
            ...(last.toolCalls ?? []),
            { callId: call_id, toolName: tool_name, argumentsJson: arguments_json, status: 'running' },
          ],
        };
      } else if ('ToolCallCompleted' in kind) {
        const { call_id, output } = kind.ToolCallCompleted;
        updated = {
          ...last,
          toolCalls: (last.toolCalls ?? []).map((tc) =>
            tc.callId === call_id
              ? { ...tc, output, status: output.startsWith('Tool execution error') ? 'error' : 'done' }
              : tc,
          ),
        };
      } else if ('PhaseCompleted' in kind) {
        updated = {
          ...last,
          streaming: false,
          phaseSummary: kind.PhaseCompleted.summary,
          tokensIn: kind.PhaseCompleted.tokens_in,
          tokensOut: kind.PhaseCompleted.tokens_out,
          cachedIn: kind.PhaseCompleted.cached_in,
        };
      } else if ('Finished' in kind) {
        // Run-wide totals must NOT clobber the per-phase numbers of the last
        // swarm phase box (tokensIn/tokensOut/cachedIn are documented as
        // THIS phase's cost and rendered as "fase ini" in AgentPanel). Only
        // the direct agent chat (message without phase fields) consumes the
        // run totals here.
        const isPhaseBox = !!(last.agentRole || last.phaseLabel);
        updated = {
          ...last,
          streaming: false,
          tokensUsed: kind.Finished.total_tokens_used,
          ...(isPhaseBox
            ? {}
            : {
                tokensIn: kind.Finished.tokens_in,
                tokensOut: kind.Finished.tokens_out,
                cachedIn: kind.Finished.cached_in,
              }),
        };
      } else if ('Error' in kind) {
        updated = { ...last, streaming: false };
      }

      messages[lastIdx] = updated;
      return { ...s, liveMessages: messages };
    });
  };
  return { wasTouched: () => touchedFiles };
}

let textBuffer = new StreamTextBuffer();
let thinkingBuffer = new StreamTextBuffer();
let flushRaf: number | null = null;

const flushStreamTextItem = (item: FlushedText) => {
  useAgent.setState((s) => {
    const idx = s.liveMessages.findIndex((m) => m.id === item.msgId);
    if (idx < 0) return s;
    const messages = [...s.liveMessages];
    messages[idx] = { ...messages[idx], content: messages[idx].content + item.text };
    return { ...s, liveMessages: messages };
  });
};

const flushStreamThinkingItem = (item: FlushedText) => {
  useAgent.setState((s) => {
    const idx = s.liveMessages.findIndex((m) => m.id === item.msgId);
    if (idx < 0) return s;
    const messages = [...s.liveMessages];
    messages[idx] = { ...messages[idx], thinking: (messages[idx].thinking ?? '') + item.text };
    return { ...s, liveMessages: messages };
  });
};

const flushStreamText = () => {
  if (flushRaf !== null) {
    cancelAnimationFrame(flushRaf);
    flushRaf = null;
  }
  const item = textBuffer.drain();
  if (item?.text) flushStreamTextItem(item);
};

const flushStreamThinking = () => {
  const item = thinkingBuffer.drain();
  if (item?.text) flushStreamThinkingItem(item);
};

const enqueueStreamDelta = (msgId: string, text: string) => {
  const overflow = textBuffer.enqueue(msgId, text);
  if (overflow) flushStreamTextItem(overflow);
  if (flushRaf === null) flushRaf = requestAnimationFrame(() => {
    flushRaf = null;
    flushStreamText();
    flushStreamThinking();
  });
};

const enqueueThinkingDelta = (msgId: string, text: string) => {
  const overflow = thinkingBuffer.enqueue(msgId, text);
  if (overflow) flushStreamThinkingItem(overflow);
  if (flushRaf === null) flushRaf = requestAnimationFrame(() => {
    flushRaf = null;
    flushStreamText();
    flushStreamThinking();
  });
};

const resetStreamBuffer = () => {
  if (flushRaf !== null) {
    cancelAnimationFrame(flushRaf);
    flushRaf = null;
  }
  textBuffer.clear();
  thinkingBuffer.clear();
};
